// Disposable browser verification using the repository's existing Playwright install.
const {chromium} = require('../../frontend/react/node_modules/@playwright/test');
const {spawn} = require('node:child_process');
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '../..');
const server = spawn(path.join(root, '.venv/Scripts/python.exe'), [path.join(__dirname, 'ui_server.py')], {cwd: root, windowsHide: true});
let browser;
(async () => {
  const port = await new Promise((resolve, reject) => {
    let buffer=''; const deadline=setTimeout(()=>reject(new Error('API fixture did not start')),20000);
    server.stdout.on('data', chunk => { buffer+=chunk; for(const line of buffer.split('\n')) {try {const value=JSON.parse(line); if(value.port){clearTimeout(deadline);resolve(value.port);}} catch {}} });
    server.on('exit', code=>{clearTimeout(deadline);reject(new Error('API fixture exited '+code));});
  });
  const url='http://127.0.0.1:'+port;
  for(let n=0;n<50;n++){try{if((await fetch(url+'/healthz')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1400,height:950}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(url);
  await page.locator('#token').fill('ui-fixture-token-'+'x'.repeat(32));
  await page.getByRole('button',{name:'Connect',exact:true}).click();
  await page.locator('#workspace-stats .stat').first().waitFor();
  await page.screenshot({path:path.join(root,'replacement/workspace-preview.png'),fullPage:true});
  assert.equal(await page.locator('#token').inputValue(),'');
  assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);
  assert(!(await page.locator('#home-apps').innerText()).includes('hidden-application'));
  const catalog=await page.evaluate(async()=> (await fetch('/source-catalog',{headers:{Authorization:'Bearer ui-fixture-token-'+'x'.repeat(32)}})).text());
  assert(!catalog.includes('do-not-display') && !catalog.includes('https://fixture.test'));
  await page.getByRole('link',{name:'Unified inbox',exact:true}).click();
  await page.locator('#inbox-records .queue-card').first().waitFor();
  assert((await page.locator('#inbox-coverage').textContent()).includes('not configured'));
  // A live signal and its recorded investigation must occupy one queue card.
  await page.route('**/alerts?*',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({checked_at:new Date().toISOString(),applications:[],next:null,items:[{application_id:'fixture-app',incident_id:'assessed-example',incident_state:'assessed',name:'Linked test signal',service:'gateway',severity:'critical',state:'firing',source_id:'fixture',fingerprint:'test',active_at:new Date().toISOString(),summary:'Synthetic linked signal'}]})}));
  await page.getByRole('button',{name:'Refresh',exact:true}).click();
  const linked=page.locator('#inbox-records .queue-card').filter({hasText:'Incident: assessed-example'});
  await linked.getByText(/1 live signal/).waitFor();assert.equal(await linked.count(),1);
  await page.locator('#inbox-views').getByRole('button',{name:/Critical/}).click();assert.equal(await page.locator('#inbox-records .queue-card').count(),1);
  await page.locator('#inbox-views').getByRole('button',{name:/Recovered/}).click();await page.getByText('No matching records',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Reset',exact:true}).click();
  await page.unroute('**/alerts?*');
  await page.evaluate(()=>{location.hash='#/alerts';});await page.getByRole('heading',{name:'Unified inbox',exact:true}).first().waitFor();
  assert.equal(await page.locator('[data-nav=inbox]').count(),1);assert.equal(await page.locator('[data-nav=alerts]').count(),0);
  await page.getByRole('link',{name:'Applications',exact:true}).click();
  await page.locator('#applications').getByRole('link',{name:'Open application'}).click();
  await page.getByText('Document discovery: context ready',{exact:true}).waitFor();
  assert((await page.locator('#overview-summary').innerText()).includes('Unknown'));
  await page.locator('#application-tabs').getByRole('link',{name:'Services',exact:true}).click();
  await page.locator('#service-search').fill('missing');
  await page.getByText('No matching services',{exact:true}).waitFor();
  await page.locator('#service-search').fill('gateway');
  await page.locator('#overview-services').getByRole('link',{name:'Investigate'}).waitFor();
  await page.locator('#application-tabs').getByRole('link',{name:'Documents',exact:true}).click();
  await page.getByRole('button',{name:'Read document contents'}).click();
  await page.locator('#overview-document-content summary').first().click();
  assert((await page.locator('#overview-document-content').innerText()).includes('Synthetic runbook'));
  await page.locator('#application-tabs').getByRole('link',{name:'Live alerts',exact:true}).click();
  await page.getByRole('button',{name:'Check live alerts'}).click();
  await page.getByText('Alert coverage unavailable',{exact:true}).waitFor();
  await page.getByRole('link',{name:'Unified inbox',exact:true}).click();
  await page.locator('#inbox-filter [name=q]').fill('does-not-exist');
  await page.getByRole('button',{name:'Apply filters'}).click();
  await page.getByText('No matching records',{exact:true}).waitFor();
  await page.locator('#inbox-filter [name=q]').fill('assessed-example');
  await page.getByRole('button',{name:'Apply filters'}).click();
  await page.locator('#inbox-records').getByRole('link',{name:'Open investigation'}).click();
  await page.getByText('Recorded state: assessed',{exact:true}).waitFor();
  assert((await page.locator('#impact').innerText()).includes('observed service errors'));
  assert((await page.locator('#rca').innerText()).includes('No confirmed root cause'));
  await page.getByRole('button',{name:'Collected evidence',exact:true}).click();
  await page.locator('#artifact-content').getByText(/window.injected=true/).waitFor();
  assert.equal(await page.evaluate(()=>window.injected),undefined);
  const recoveredFixture=await page.evaluate(async()=> (await fetch('/applications/fixture-app/incidents/assessed-example',{headers:{Authorization:'Bearer ui-fixture-token-'+'x'.repeat(32)}})).json());
  recoveredFixture.state='recovered';recoveredFixture.incident_id='recovered-fixture';
  recoveredFixture.result.impact.summary='Fixture service rejected requests before repair.';
  recoveredFixture.result.impact.status='current_service_failure_confirmed';
  recoveredFixture.result.rca.summary='Test maintenance was enabled.';
  recoveredFixture.result.rca.confirmed_cause='Test maintenance was enabled.';
  recoveredFixture.result.rca.status='current_condition_confirmed';
  recoveredFixture.result.rca.next_checks=['Check the original failure.'];
  recoveredFixture.result.resolution={status:'recovered',reason:'Two fresh healthy observations confirmed recovery',action_id:'fixture-action'};
  await page.route('**/incidents/recovered-fixture?*',route=>route.fulfill({contentType:'application/json',body:JSON.stringify(recoveredFixture)}));
  await page.evaluate(()=>{location.hash='#/incidents/fixture-app/recovered-fixture';});
  await page.getByText('Recorded state: recovered',{exact:true}).waitFor();
  assert((await page.locator('#freshness').innerText()).includes('/ recovery verified'));
  assert(!(await page.locator('#freshness').innerText()).includes('not verified'));
  assert.equal(await page.locator('#journey .complete').count(),7);
  assert.equal(await page.locator('#impact-title').textContent(),'Impact before recovery');
  assert.equal(await page.locator('#rca-title').textContent(),'Cause identified before recovery');
  assert(!(await page.locator('#rca').innerText()).includes('Next check:'));
  assert.equal(await page.locator('#rca').getByText('Recorded at diagnosis: Test maintenance was enabled.',{exact:true}).count(),1);
  assert(!(await page.locator('#investigation-origin').innerText()).includes('does not establish that a fault'));
  await page.evaluate(()=>{location.hash='#/incidents/fixture-app/assessed-example';});
  await page.getByText('Recorded state: assessed',{exact:true}).waitFor();
  assert.equal(await page.locator('#impact-title').textContent(),'Impact assessment');
  await page.screenshot({path:path.join(root,'replacement/ui-verification.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.getByRole('link',{name:'Onboard application',exact:true}).click();
  const form=page.locator('#onboard-form');
  await form.locator('[name=application_id]').fill('browser-app');
  await form.locator('[name=services]').fill('gateway');
  await form.locator('[name=root]').selectOption('docs');
  await form.getByRole('button',{name:'Start discovery'}).click();
  await page.getByText('Document discovery: discovery queued',{exact:true}).waitFor();
  await page.getByRole('link',{name:'New investigation',exact:true}).click();
  const incident=page.locator('#incident-form');
  await incident.locator('[name=incident_id]').fill('browser-incident');
  await incident.locator('[name=start]').fill('2026-09-01T10:00');
  await incident.locator('[name=end]').fill('2026-09-01T10:10');
  await incident.getByRole('button',{name:'Queue investigation'}).click();
  await page.getByText('Recorded state: waiting for context',{exact:true}).waitFor();
  await page.reload();
  await page.locator('#token').fill('ui-fixture-token-'+'x'.repeat(32));
  await page.getByRole('button',{name:'Connect',exact:true}).click();
  await page.getByText('Recorded state: waiting for context',{exact:true}).waitFor();
  await page.route('**/incidents/browser-incident?*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Synthetic source unavailable'})}));
  await page.getByRole('button',{name:'Refresh investigation',exact:true}).click();
  await page.getByText('Refresh failed. Displayed information may be stale.',{exact:true}).waitFor();
  await page.getByRole('link',{name:'Workspace settings',exact:true}).click();
  await page.getByText('Available document roots',{exact:true}).waitFor();
  assert(!(await page.locator('#screen-settings').innerText()).includes('do-not-display'));
  await page.getByRole('link',{name:'Document library',exact:true}).click();
  await page.locator('#library-apps .app-card').first().waitFor();
  await page.evaluate(()=>{location.hash='#/applications/fixture-app/registration';});
  await page.locator('#registration-editor textarea').waitFor({state:'visible'});
  await page.locator('#registration-editor textarea').fill('gateway, added-worker');
  await page.getByRole('button',{name:'Save registration and rediscover',exact:true}).click();
  await page.getByText('Document discovery: discovery queued',{exact:true}).waitFor();
  const updated=await page.evaluate(async()=> (await fetch('/applications/fixture-app',{headers:{Authorization:'Bearer ui-fixture-token-'+'x'.repeat(32)}})).json());
  assert.deepEqual(updated.config.services,['gateway','added-worker']);
  assert.equal(updated.config.document_sources[0].root,'docs');
  assert.deepEqual(updated.config.telemetry_sources,['fixture-source']);
  const original=await page.evaluate(async()=> (await fetch('/applications/fixture-app/incidents/assessed-example',{headers:{Authorization:'Bearer ui-fixture-token-'+'x'.repeat(32)}})).json());
  assert.equal(original.state,'assessed');assert(original.baseline.artifact_ref);
  await page.evaluate(()=>{location.hash='#/incidents/fixture-app/assessed-example';});
  await page.getByText('Recorded state: assessed',{exact:true}).waitFor();
  assert((await page.locator('#impact').innerText()).includes('Nonzero error-rate samples'));
  // Registration above is rediscovering, so the rerun must report that gate.
  await page.getByRole('button',{name:'Rerun investigation',exact:true}).click();
  await page.getByText('Wait for document context to become ready',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await page.locator('#login').waitFor({state:'visible'});
  assert.equal(await page.locator('#artifact').textContent(),'');
  assert.deepEqual(errors,[]);
  const report={real_api:true,isolated_sqlite:true,browser_passed:true,onboarding:true,incident_submission:true,
    recovered_history_consistent:true,alerts_inbox:true,versioned_registration:true,historical_incident_baseline:true,routed_workspace:true,inbox_search:true,service_filter:true,deep_link_after_login:true,settings:true,
    assessment_display:true,documents_without_incident:true,evidence_xss_rejected:true,tenant_scope:true,source_secrets_hidden:true,stale_state_reported:true,mobile_layout:true,broker_mocked:true};
  fs.writeFileSync(path.join(root,'replacement/ui-verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.kill();});
